//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeavingTable
    {
        public int EmployeeLeavingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string LeavingReason { get; set; }
        public string LeavingComments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual StaffTable StaffTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
